name: a4s_sealer_node
services:
  a4s_sealer:
    container_name: a4s_sealer
    image: ghcr.io/ad-sdl/a4s_sealer_module
    network_mode: host
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - path: .env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/a4s_sealer_module:latest
        - ghcr.io/ad-sdl/a4s_sealer_module:dev
    command: python -m sealer_rest_node
    volumes:
      - ./settings.yaml:/home/madsci/settings.yaml
      - ./.madsci:/home/madsci/.madsci
