name: a4s_sealer_node
services:
  a4s_sealer:
    container_name: a4s_sealer
    image: ghcr.io/ad-sdl/a4s_sealer_module
    network_mode: host
    privileged: true
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/ad-sdl/a4s_sealer_module:latest
        - ghcr.io/ad-sdl/a4s_sealer_module:dev
    command: python -m sealer_rest_node --node_definition /home/madsci/definitions/sealer_node.node.yaml
    volumes:
      - ./definitions:/home/madsci/definitions/
